apiVersion: v1
kind: Secret
metadata:
  name: traefik-ingress-default-tls
  namespace: kube-system
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.traefik_tls_crt }}
  tls.key: {{ .Values.traefik_tls_key }}
