---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-server-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.monitoring_storage_class }}
  storageClassName: {{ .Values.monitoring_storage_class }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.monitoring_storage_size_grafana }}
